# Exercise 2 

# Numerical methods for Python

In our first exercise, we had a look at some basic Python packages and first simple scientific examples for plotting functions. The methods that we used before were mainly based on pure Python objects, especially on lists. These object types are useful for many Python programming methods and very flexible, but highly inefficient when used for numerical calculations.

Python has an integrated extension library `numpy` (for: numerical Python) that provides a lot of methods and objects for more efficient numerical calculations.

However, in order to use the full efficiency gain of these methods, they have to be used in an appropriate way: in vectorised operations. Basically, this means that, instead of iterating over several entires to perform a calculation (say, adding two vectors), it is better to add the arrays directly, with appropriate methods.

Again, this will sound very familiar to anyone who knows Matlab. And, again, this is no coincidence, as the underlying programming style is identical and even mostly based on the same linear algebra software packages, the famous LaPACK 
(http://en.wikipedia.org/wiki/LAPACK) and BLAS.

We will start with a quick tour of the `numpy` package and the new object types that it provides and then compare the use of those methods to the simple Python implementations.


## Preliminary: importing Python libraries

Before we get started with the Python extension packages, a quick introduction into how these packages/ libraries are actually included in your program. In the last exercise notebook, you already saw the implementation:

    from pylab import *
    
This line imports all the functions from the `pylab` library into the current program. More specifically, it imports all the functions into the current namespace. This means that you can call any function from that library directly in your program. As an example, in the last exercise notebook we then used the `plot` command from this library:

    plot(random_numbers, 'o')
    
Although it is very convenient to have the functions readily available in the same namespace, it can cause serious problems - especially if functions with a name are imported that already exist in the namespace. In this case, confusion is guaranteed!

So, the safer way is to import either:

1. only single functions from a library:
    
        from numpy.random import randint
    
2. to import the library with its own reference namespace, e.g.:

        import numpy
    
For the case of the second implementation, the functions of the libraries can then be accessed with the dot-notation, e.g.:

    numpy.array([2,3])
    
We will see a lot more examples below. A convenient method is to abbreviate the imported library with an alias name. For example, very commonly used is:

    import numpy as np

The functions can then be accessed with:

    np.array([2,3])
    
Depending on how often you have to use a specific function, this method can save quite a bit of time. Just make sure that you use a meaningful name as alias - and that you do not accidentally overwrite a variable you created before...

Try out those methods for module import:


In [3]:
# use the import method to import a module"
import numpy as np

## `numpy` basics

<hr style="border-width: 2px;">

A note to experienced Matlab users: I am going here through the very basics of `numpy` - a lot of the methods will look very familiar to you (see more comments below). If you feel confident, you can skip most of the `numpy` introduction and have a look at a direct comparison betwen Matlab and `numpy` methods, nicely summarised here:

http://wiki.scipy.org/NumPy_for_Matlab_Users

However, please have a look through this notebook anyway - and experiment with some of the methods to see the little (but quite important) differences...
<hr style="border-width: 2px;">



The Python package `numpy` mainly contains methods to work efficiently with arrays and matrices. In addition, it provides a range of methods for typical operations that are often required in numerical analyses, like random number generation and several efficient linear algebra methods.

### n-dimensional arrays

At the core of `numpy` are multi-dimensional arrays. There are two very important differences between Python lists and `numpy` arrays:
1. `numpy` arrays always contain elements of the same type (e.g. only integer values) - whereas Python lists can contain any elements;
2. The memory for `numpy` arrays is allocated whereas Python lists operate on a dynamic memory. In practice this means that:
    - you should avoid to append elements to an array (as we have done before with Python lists - the append() function).
    - if you need a long list of known length with (yet) unknown elements, then pre-define the list as an empty list (examples will follow).

We will start looking at methods to generate `numpy` array objects, first. The simplest way to create an array object is actually to directly convert a Python list to an array with the `np.array()` function (Note: I'll use `np` as the common abbreviation for `numpy` methods in the following):




In [4]:
a_list = range(100)
a_array = np.array(a_list)

Here are some methods and attributes of this object. The dimensions of an array object is stored in:

In [5]:
a_array.shape

(100L,)

We can take an array, reshape it and return it in a different dimension, e.g.:

In [7]:
b_array = a_array.reshape(2,50)
print b_array.ndim
print b_array

2
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]


The shape of an array is stored in the variable `shape`:

In [6]:
print a_array.shape
print b_array.shape

(100,)
(2, 50)


### Array types

As mentioned above, an important difference to standard Python lists is that arrays always contain the same data type. The array type is stored in the array variable `dtype`, e.g.:


In [8]:
new_array = np.array([2, 2, 1], dtype="int32")

In [14]:
new_array[0] = 356167233123


In [15]:
new_array

array([-315052445,          2,          1], dtype=int32)

We can see that, in the first example, we created an array with elements of integer type. 

Try what happens if you now assign a float value to an array element:

In [16]:
a_array[2] = 3.2
print a_array[2]

3


The value is automatically converted to the type of the array! This behaviour is useful, but can lead to problems if you are not careful in generating arrays!

If you want to create an array of a specific type (to avoid these problems - or to get more efficient memory use), you can define the type with the `dtype` argument in most `numpy` array generation functions:


In [17]:
a2_array = np.array(a_list, dtype=float)

If we now assign a float value, we get what we expected:

In [74]:
a2_array[2] = 3.2
print a2_array[2]

### Creating arrays with `numpy` functions

Another (and often more efficient) way to create `numpy` arrays is to use the methods provided by the package. As opposed to the Python `range()` function, we can use its `numpy` equivalent to directly get an array:

In [75]:
c_array = np.arange(100)
print c_array
print type(c_array)
print c_array.dtype

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
<type 'numpy.ndarray'>
int64


Also here, you can use the `dtype` keyword to enforce a specific variable type in the array, e.g.:

In [18]:
c2_array = np.arange(100, dtype=complex)
print c2_array
print c2_array.dtype

[  0.+0.j   1.+0.j   2.+0.j   3.+0.j   4.+0.j   5.+0.j   6.+0.j   7.+0.j
   8.+0.j   9.+0.j  10.+0.j  11.+0.j  12.+0.j  13.+0.j  14.+0.j  15.+0.j
  16.+0.j  17.+0.j  18.+0.j  19.+0.j  20.+0.j  21.+0.j  22.+0.j  23.+0.j
  24.+0.j  25.+0.j  26.+0.j  27.+0.j  28.+0.j  29.+0.j  30.+0.j  31.+0.j
  32.+0.j  33.+0.j  34.+0.j  35.+0.j  36.+0.j  37.+0.j  38.+0.j  39.+0.j
  40.+0.j  41.+0.j  42.+0.j  43.+0.j  44.+0.j  45.+0.j  46.+0.j  47.+0.j
  48.+0.j  49.+0.j  50.+0.j  51.+0.j  52.+0.j  53.+0.j  54.+0.j  55.+0.j
  56.+0.j  57.+0.j  58.+0.j  59.+0.j  60.+0.j  61.+0.j  62.+0.j  63.+0.j
  64.+0.j  65.+0.j  66.+0.j  67.+0.j  68.+0.j  69.+0.j  70.+0.j  71.+0.j
  72.+0.j  73.+0.j  74.+0.j  75.+0.j  76.+0.j  77.+0.j  78.+0.j  79.+0.j
  80.+0.j  81.+0.j  82.+0.j  83.+0.j  84.+0.j  85.+0.j  86.+0.j  87.+0.j
  88.+0.j  89.+0.j  90.+0.j  91.+0.j  92.+0.j  93.+0.j  94.+0.j  95.+0.j
  96.+0.j  97.+0.j  98.+0.j  99.+0.j]
complex128


Other commonly used methods are `np.linspace` and `np.logspace` to create arrays with increasing elements for a defined range (similar to Matlab, again):

In [19]:
d_array = np.linspace(0,1,11)
print d_array
e_array = np.logspace(0,3,10)
print e_array

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]
[    1.             2.15443469     4.64158883    10.            21.5443469
    46.41588834   100.           215.443469     464.15888336  1000.        ]


In [21]:
np.arange(0,1.01,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

If you want more details on the functions, remember the useful IPython help call:

`np.logspace??`

### Empty arrays and arrays filled with ones

If you need an array to store data that is yet unknown (but you know the array length), then you can create an empty array with defined shape (and, optionally, type):

In [23]:
shape = (10,)
empty_array = np.empty(shape) #, dtype=float64)
print empty_array

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Note that the array elements are not necessarily zero, so don't perform any operations on it. If you really want a zero array, it is better to use the `np.zeros` method:

In [24]:
zeros_array = np.zeros(shape)
print zeros_array

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Similarly, there is the very useful `np.ones` method:

In [26]:
ones_array = np.ones(shape) * 100
print ones_array

[ 100.  100.  100.  100.  100.  100.  100.  100.  100.  100.]


It is often the case that you need an array with, say, empty elements that has the same shape as another array (for example, if you want to store results for some operation on that array). You can determine and use the shape of a different array with the methods:

In [160]:
x = np.arange(10)
empty_again = np.empty_like(x)
zeros_again = np.zeros_like(x)
ones_again = np.ones_like(x)

## Extracting elements of arrays

Extracting elements from 1-D arrays is similar to extracting elements from Python lists, e.g. for single elements, we can use:

In [109]:
print a_array[5]

And for array slices, a `[from_element:to_element]`-logic:

In [113]:
print a_array[10:20]

Note: Python understands negative array (and list) indexes as going from the last element `[-1]` backwards, so the last two elements are: 

In [128]:
print a_array[-2:100]

When extracting slices, you can also define the index increment:

In [121]:
print a_array[0:10:2]

And this functionality can be useful if you want to reverse the order of elements in an array:

In [125]:
a_array_reversed = a_array[::-1]

### Extracting elements from multidimensional arrays

If you have an array of higher dimension, then the elements are extracted with indexes (or slices) separated by a comma:

In [27]:
md_array = np.arange(20).reshape(4,5)
print md_array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
md_array[0,1] # first row, second element

1

In [135]:
md_array[0,:] # extract entire first row

array([0, 1, 2, 3, 4])

In [136]:
md_array[:,0] # extract first column

array([ 0,  5, 10, 15])

In [140]:
md_array[2:4,1:4] # extract a sub-md-array of dimenion 2: 
                  # elements in columns 1,2,3 of rows 2,3

array([[11, 12, 13],
       [16, 17, 18]])

In [29]:
md_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
md_array < 3

array([[ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

### Extracting elements with a boolean array

Quite often it happens that you want to extract elements from an array at locations that are determined with a boolean operation, for example all elements that are within a certain range of values. You can achieve it in `numpy` with actually passing a boolean array to the index brackets:

In [44]:
n = np.array([0,1,0,0,0], dtype=bool)

In [45]:
print n

[False  True False False False]


In [162]:
f_array = np.arange(5)
boolean_array = np.array([False, False, True, False, True])
print f_array[boolean_array]

[2 4]


You can also create the boolean array directly with an inequality operation on an existing array, e.g.:

In [165]:
g_array = np.arange(100)
another_boolean_array = g_array < 20
print g_array[another_boolean_array]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


And you can also combine boolean arrays by simple multiplication for multiple constraints:

In [169]:
h_array = np.arange(100)
lower_bound = h_array > 10
upper_bound = h_array < 20
combined_bounds = lower_bound * upper_bound
print h_array[combined_bounds]

[11 12 13 14 15 16 17 18 19]


## Vectorised operations

A core functionality for an efficient use of `numpy` methods is the use of vectorised operations - whenever this is possible. What this means it that, instead of performing operations on single elements in a vector (with, for example, a `for`-loop), the operations are performed on the entire vector with a suitable function.

As an example, let's say you want to calculate the sine of values in a range  [0,2$\pi$].


In [126]:
x = np.arange(0, 2 * np.pi, 0.1)

In [47]:
for x in [30,10,20]:
    print x


30
10
20


The iterative way is:

In [25]:
y = np.empty_like(x)
for i,xx in enumerate(x):
    y[i] = sin(xx)

In [12]:
x = np.random.rand(10)
print x
for i,x in enumerate(x):
    print "i",i
    print "x",x

[ 0.16669343  0.18045669  0.37991499  0.58636995  0.86348955  0.40696016
  0.64009479  0.67812991  0.95338688  0.67901884]
i 0
x 0.166693433222
i 1
x 0.180456689366
i 2
x 0.379914990535
i 3
x 0.586369949071
i 4
x 0.86348954583
i 5
x 0.406960159404
i 6
x 0.640094793731
i 7
x 0.678129914783
i 8
x 0.953386879054
i 9
x 0.679018837002


We iterate over all elements in the x-array, then calculate the sine value for this element, and pass it to the appropriate position in the y-array. If you like, create a quick plot of those values to check if we have done it correctly (always a good idea):

In [48]:
x = np.arange(0,2*np.pi,0.1)

We do get the correct result, but the implementation is not very efficient. A better way to get the same result is to use the `np.sin` function instead of the standard Python `sin` function: the `numpy` function can operate on all vector elements with one call (it is a *vectorised* function).

In addition, if we use the vectorised function, we do not have to create an empty `y` array first but can directly assign the result back to the array:



In [52]:
y = np.sin(x)

In [55]:
a_list = [1,2,3]
b_list = [4,5,6]
c_list = a_list + b_list
print c_list

[1, 2, 3, 4, 5, 6]


Yes, it's as simple as that! In addition, the basic mathematical operations (+,-,\*,/) can be directly applied to two array objects:

In [57]:
x = np.arange(0,1,0.2)
print x
x = x + x
print x

[ 0.   0.2  0.4  0.6  0.8]
[ 0.   0.4  0.8  1.2  1.6]


A note for Matlab users: in Matlab, this behaviour is implemented in the "." (dot)-operators - with `numpy`, it is the standard behaviour.

Another useful function to know: if you want to add/ subtract/ multiply/ divide each element in an array with a scalar, you can simply perform the operation for the array with:


In [105]:
x = x + 2

For these operations (and for the standard Python equivalents, as well), there is an often used shorthand that performs the same operation:

In [106]:
x += 2

I mentioned before that the `numpy` functions are not only easier to work with but also more efficient. So the next logical question to ask is: what is the gain in efficiency between those two types of implementation - and, also, comparing a `numpy` implementation of a function to pure Python? 

We will have a look at ways to compare code in the following section.

## Short intermezzo: timing code execution

Before we start to compare implementation, here a quick introduction to a very useful IPython magic function (already mentioned during Exercise 1): the `%timeit` function. It can be used to determine the execution time for any command that is preceding its call in the same line, or even for an entire notebook cell if it is used as the cell magic function `%%timeit`.

See also examples and descrition in:

http://ipython.org/ipython-doc/dev/interactive/tutorial.html

A useful behaviour of this function is that it executes functions that are quite fast for a large number of times to get a good estimate of the execution time.

Try it out with a function (or code snippet) of your choice:

In [58]:
%timeit np.sin(.2) # <- add your function here, for example sin(2.)

1000000 loops, best of 3: 1.08 µs per loop


We are using the `%timeit` function now to compare the efficiency of pure python algorithms compared with the (vectorised) `numpy` implementation.

We first write a simple function that adds two lists together, element by element:

In [3]:
def add_elements_in_list(a,b):
    """basic Python implementation"""
    c = []
    for i in range(len(a)):
        c.append(a[i] + b[i])
    return c

For the test, we simply create two lists:

In [4]:
# create some long lists to add
a = []
b = []
for i in range(1000):
    a.append(i)
    b.append(i)

We then use the `%timeit` function to evaluate the execution time for the function:

In [5]:
%timeit add_elements_in_list(a,b)

1000 loops, best of 3: 194 µs per loop


In my case, the execution of the function required approximately 180 $\mu$s. 

Now, we are going to transform those lists into numpy arrays and repeat the addition with the appropriate `numpy` function. As stated above, in the concept of `numpy`, adding two vectors element-wise is simply the normal addition operation:

In [6]:
# transform into numpy arrays
a_np = np.array(a)
b_np = np.array(b)

In [7]:
%timeit a_np + b_np

1000000 loops, best of 3: 1.91 µs per loop


On my laptop, the execution time was now reduced to 1.8 $\mu s$: the `numpy` implementation is faster by a factor of 100!

Although you might not really care if a code executes in a fraction of a second or a really small fraction of a second (as in this case) - having code execute fast is an important consideration once we get to more complex simulations. So, it is best to get used to efficient programming styles early-on - it will later make your life easier!

## Some more useful operations with `numpy`

We had a look at several array methods before and discussed the use of vectorised operations.

### Basic array operations

Some useful basic array operations are:

In [186]:
i_array = [1,3,1,24,1,234,1]
print i_array
print np.sum(i_array) # determine the sum
print np.sort(i_array) # return sorted version of the array
print np.cumsum(i_array) # cummulative sum of elements
print np.min(i_array) # minimum value
print np.max(i_array) # maximum value

[1, 3, 1, 24, 1, 234, 1]
265
[  1   1   1   1   3  24 234]
[  1   4   5  29  30 264 265]
1
234


### Basic linear algebra

We will have a look at some of these methods in more detail when we go along through our exercise, here a quick look at some important functions:


In [204]:
import numpy.linalg as linalg
a = np.arange(1.,5).reshape(2,2)
print a # original array
print a.transpose() # transpose 
print linalg.inv(a) # inverse of a
b = np.eye(2) # 2x2 unit matrix, "I"
print b
c = np.dot(a,a) # dot/ matrix product
print c
ta = np.trace(a) # the trace of a
print ta

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.  0.]
 [ 0.  1.]]
[[  7.  10.]
 [ 15.  22.]]
5.0


And for solving matrix equations and calculating eigenvalues and -vectors:

In [207]:
y = array([[5.], [7.]])
print linalg.solve(a,y)
print linalg.eig(a)

[[-3.]
 [ 4.]]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


Again, we will use these (and more) methods later on - and explain them there again in more detail.

### Basic random numbers and statistics

Methods to generate several types of random numbers are available in the package `numpy.random`. For example:

In [218]:
import numpy.random as random
uniform_rns = random.uniform(0,1,10) # generate ten uniform random numbers between [0,1]
print uniform_rns
integer_rns = random.randint(20,30,5) # five random integers between [20,30]
print integer_rns
normal_rns = random.randn(10) # draw 10 samples from standard normal distribution
print normal_rns

[ 0.95994111  0.26214619  0.6008533   0.76835981  0.05550344  0.83210688
  0.51226463  0.44370527  0.91939312  0.67598953]
[25 24 23 28 29]
[ 1.68648833 -2.23204029 -0.20045281  1.23979788  0.03520195 -0.89243789
  1.00049372  0.0367333  -0.15230444 -0.61576343]


And to determine the common statistics, you can simply use:

In [219]:
print np.mean(uniform_rns)
print np.std(normal_rns)
print np.var(normal_rns)

0.603026328411
1.07726601935
1.16050207645


## A note on: Copies and references

Some of you might be familiar with the concept of references to variables (or pointers to memory locations of variables in C). Basically, a reference is creating a link to a variable. This is very useful, for example if you want to pass a variable to a function: instead of having to copy the entire variable (and, therefore, using up potentially quite a bit of extra memory), only the reference is passed.

In Python, the default behaviour can, unfortunately, be sometimes confusing - so here a quick example on what to consider.

First, we create a standard Python object: a simple integer:



In [59]:
a_int = 2

We assign that variable to a new variable:

In [60]:
b_int = a_int

Now, we assign a new value to the variable `a_int`:

In [61]:
a_int = 1000

Have a look what happened with the variable `b_int`:

In [62]:
b_int

2

Ok, this is probably what you have expected: the value of the variable `b_int` is still as before - we created a true copy of variable `a_int` when we assigned it to `b_int`.

Let's have a look what happens when we use a Python list object:

In [63]:
a_list = [1,2,3]
b_list = a_list
# now, change an entry in a_list:
a_list[2] = 1000
a_list

[1, 2, 1000]

That's fine - so what happened to the other list? Have a look:

In [64]:
b_list;

The value in `b_list` changed, as well! So, in this case, we actually created a references to the list object - and not a copy - when we assigned `b_list = a_list`!

The same behaviour is implemented for the `numpy.array` objects that we are going to use a lot in the course of this exercise:


In [65]:
a_array = np.array([1,2,3])
b_array = a_array
a_array[2] = 1000
print a_array
print b_array

[   1    2 1000]
[   1    2 1000]


It is important to be aware of this behaviour and keep it in mind when you write your programs!

Finally, if you really want to create a copy - and not a reference - then there are several options. For Python lists, the simples way is to actually copy the list entries:

In [16]:
c_list = [1,2,3]
# we now de-reference the entire list values and assign them to the new variable:
d_list = c_list[:]
c_list[2] = 128734
print c_list, d_list

[1, 2, 128734] [1, 2, 3]


For `numpy.array` objects, we can use an array method to get a copy:

In [17]:
c_array = np.array([1,2,3])
d_array = c_array.copy()
c_array[2] = 1234
print c_array, d_array

[   1    2 1234] [1 2 3]


Finally, if you want to get a copy of any type of object, you can also use the method `copy.deepcopy`:

In [18]:
import copy

In [19]:
# works for lists...
c_list = [1,2,3]
d_list = copy.deepcopy(c_list)
c_list[2] = 128734
print c_list, d_list
# ... as well as arrays...
c_array = np.array([1,2,3])
d_array = copy.deepcopy(c_array)
c_array[2] = 1234
print c_array, d_array
# ...as well as any other type of objects!

[1, 2, 128734] [1, 2, 3]
[   1    2 1234] [1 2 3]


In [20]:
from IPython.core.display import HTML
css_file = 'nre_style_2.css'
HTML(open(css_file, "r").read())

### Creation of matrices

In [4]:
import numpy as np
# 1. define dimension
N=10

# 2. create a NxN matrix with zeros
shape=(N,N)
A = np.zeros(shape)
B = A
# 3. modify matrix
i,j = np.indices(shape)
A[i==j] = -2.
A[i-1==-j] = 3.
A[i+1==j] = 4.

print A



[[-2.  4.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3. -2.  4.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2.  4.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2.  4.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -2.  4.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -2.  4.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -2.  4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -2.  4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -2.  4.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -2.]]
