# Tutorial 2: Numpy and Matplotlib for Dummies®

Welcome back to Python for Dummies®. Since I am aware that listen to a honeyed voice going through functions is the best way to sleep *la siesta* at 3 pm, from now on the tutorials will be even more learning by doing. In this notebook we will learn the the syntaxis and how to create the functions that you will need to hack the Assignment 2.

### Exercise 1: Importing, once more time

You have done it 30 times so far but can you doing it without checking out? Import numpy and matplotlib

In [3]:
from IPython.core.display import HTML
css_file = r'C:\Users\Miguel\workspace\nre_style_3.css' # Here you have to write your path!
HTML(open(css_file, "r").read())

#your code here:



In [ ]:
x = np.random.rand(5)
y = np.random.rand(5)
print(x, y)

Try to plot x and y. Can you visualize it?

In [ ]:
#your code here:


### Exercise 2: Numpy vector and operations
#### Exercise 2.1: Creation of numpy arrays

Let's play with the creation of arrays and their basic operations:

1. Create a matrix A with shape 5(rows)x10(columns) that follows the serie: 0,2,4,6....
```
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
```
 
2. Create a matrix B with same shape that goes from 584.22 to 132.54 (without using a calculator)
```
[[ 584.22        575.00204082  565.78408163  556.56612245  547.34816327
   538.13020408  528.9122449   519.69428571  510.47632653  501.25836735]
 [ 492.04040816  482.82244898  473.6044898   464.38653061  455.16857143
   445.95061224  436.73265306  427.51469388  418.29673469  409.07877551]
 [ 399.86081633  390.64285714  381.42489796  372.20693878  362.98897959
   353.77102041  344.55306122  335.33510204  326.11714286  316.89918367]
 [ 307.68122449  298.46326531  289.24530612  280.02734694  270.80938776
   261.59142857  252.37346939  243.1555102   233.93755102  224.71959184]
 [ 215.50163265  206.28367347  197.06571429  187.8477551   178.62979592
   169.41183673  160.19387755  150.97591837  141.75795918  132.54      ]]
```
3. $c= \sum_{i=1}^n A * \sum_{i=1}^n B$

In [ ]:
#Your code here:



#### Exercicse 2.2: Looking for the value in the chaos

Several timers we will find lomg list of numbers with a complete chaotic structure where we will need to be able to find different stuff:

1. Find the maximum value of D
2. Find the minimum value of D
3. Find the  position of the maximum avlue of D
4. Find the second bigger value of D
5. Make an array F that contains only the values over 60
6. Make an array G that does not contain the maximum value

In [ ]:
D = np.random.randint(0,100,1000)
#your code here


Make a function that returns the values of E above and below x. e.g. 

```python
x = 5
E = [0,40,2,11,55]
return 2,11
```

In [ ]:
x = np.random.randint(0,100)
E = np.random.randint(0,100,5)
print(x,E)
#your code here:



### Exercise 3: Manipulation of matrices

Being able to create any type of matrix can be more challenger than it looks. Do not make tha arrays manually (value by value) feel the Python. Try to get the following:

1.
```
[[ 2.  2.]
 [ 2.  2.]]

```

In [ ]:
#your code here:

2.
```
[[ 2.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]]
```

In [ ]:
#your code here:

3.
```
[[ 1.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  3.]]
```

In [ ]:
#your code here:

4.
```
[[ 1.  0.  0.]
 [ 1.  2.  0.]
 [ 1.  0.  3.]]
```

In [ ]:
#your code here:

5.
```
[[ 1.  0.  0.  0.  2.]
 [ 1.  2.  0.  0.  3.]
 [ 1.  2.  1.  0.  4.]]
```

In [ ]:
#your code here:

6.
```
[[-4.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1. -4.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  1. -4.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0. -4.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1. -4.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1. -4.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0. -4.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  1. -4.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1. -4.]]
```

In [ ]:
#your code here:

### Exercise 4: Plotting

Learn how to plot in Python looks a bit like this:

![want die](plotlern.png)

However, there is a solution for all your problems! (nearly)

http://nbviewer.ipython.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-4-Matplotlib.ipynb

So here in Python for Dummies® we will try to go step by step until you will be able to create the Cathedral of Cologne  in 3D.

#### Exercise 4.1: Do not start the house from the roof. One dimension mastery.

Since we do not want to waste time, lets try to make science out of this.

- Make a plot with shape of a house

![house](house.png)

2. Set a title
3. Set labels to axes
3. Set a Grid
3. Set the name of lines to -> house
4. Create a vertical line from the top of your roof to the floor. Dashed ----
5. Now add a nice tree close to the house
6. Make the top of the tree transparent
7. Color the roof
7. Last but not least: Make a fence with five arrows

The final result should look kind of: 

![houseCom](houseCom.png)

In [ ]:
#your code here:



#### Exercise 4.2: 3D plotting

Plotting in 3D is a bit tricky since we have to start to think in matrices. Our plot functions will need now 3 main atributes (3D), x and y that will create basically the frame and Z that will give the value to that frame. The weird part of these is that you need this format:

```
Rx = [[0 1 2 3 4 5]
     [0 1 2 3 4 5]
     [0 1 2 3 4 5]
     [0 1 2 3 4 5]
     [0 1 2 3 4 5]
     [0 1 2 3 4 5]]
     
Ry = [[0 0 0 0 0 0]
     [1 1 1 1 1 1]
     [2 2 2 2 2 2]
     [3 3 3 3 3 3]
     [4 4 4 4 4 4]
     [5 5 5 5 5 5]]
```

Our values of Z must be also given in a matrix of the same shape in this case 6x6:

```
Zr = [[0 0 0 0 0 0]
     [0 0 0 0 0 0]
     [0 0 0 0 0 0]
     [0 0 0 0 0 0]
     [0 0 0 0 0 0]
     [0 0 0 0 0 0]]
```

So now, we have all the ingredienst to make a nice mountain using:
```python

plt.contourf(Rx, Ry, Zr,)

```

In [ ]:
#your code here: